### ISSUE TITLE
Remove Eigen::Nullary* operators

### ISSUE THREAD

**Issue by claudiofantacci** [robotology/bayes-filters-lib#2]
Nullary operators causes problems (compilation errors) with Eigen3 version lower than 3.3.

**Comment by traversaro** [comment]
Compatibility with the Eigen3 shipped with Ubuntu 16.04 would be indeed extremely convenient for deployment.

**Comment by claudiofantacci** [comment]
I agree. Note that also Trusty is affected by this problem.
Nullary operators are used in the library for random numbers.
I think I will roll back to STL + Eigen base operators.

**Comment by claudiofantacci** [comment]
This issue has been solved in release [`0.6.2.0`](https://github.com/robotology/bayes-filters-lib/blob/master/CHANGELOG.md#dependencies).
