### ISSUE TITLE
Implement `getLikelihood` in `*KFCorrection`

### ISSUE THREAD

**Issue by claudiofantacci** [robotology/bayes-filters-lib#42]

**Comment by claudiofantacci** [comment]
@xEnVrE let me know if you are able to implement this within this week 👍

**Comment by xEnVrE** [comment]
@claudiofantacci Sorry but for some reasons I wasn't receiving notifications. Yes I'll be able to do it.

**Comment by xEnVrE** [comment]
At the moment this is addressed in #60 for classes `KFCorrection` and `UKFCorrection`.

For the class `SUKFCorrection`, some extra work is required (see #61).

**Comment by claudiofantacci** [comment]
Closed by #60.
