### ISSUE TITLE
Implement resize method for `Gaussian*` and derived classes 

### ISSUE THREAD

**Issue by claudiofantacci** [robotology/bayes-filters-lib#48]

**Comment by claudiofantacci** [comment]
Hey @xEnVrE, please let me know if you are able to implement this within this week 👍

**Comment by xEnVrE** [comment]
@claudiofantacci Sorry but for some reasons I wasn't receiving notifications. Yes I'll do it. :+1:

**Comment by claudiofantacci** [comment]
Closing after #62.
