### ISSUE TITLE
Implement evaluation of a Gaussian density in `utils`

### ISSUE THREAD

**Issue by xEnVrE** [robotology/bayes-filters-lib#59]
There are several places where we are evaluating a Gaussian density, namely
- `GaussianLikelihood::likelihood`
- `WhiteNoiseAcceleration::getTransitionProbability`
- `GPFCorrection::evaluateProposal`

and we will have other such as `*KFCorrection::getLikelihood` as per #42.

Can we have a utility function in `utils.cpp` for this? Of course, one day we may end up having a class for `distributions`.

**Comment by claudiofantacci** [comment]
Yes! Let's move this in utility for now, but I think we might need something more structured.
Maybe after we implement noise classes we can come up with a better solution.

**Comment by xEnVrE** [comment]
Ok, then let's say we can have a PR for adding this to `utils` and using it in all the places where we need it plus in `*KFCorrection`. Is this fine?

**Comment by claudiofantacci** [comment]
Sure. Are you willing to do it?

**Comment by xEnVrE** [comment]
Yes!

**Comment by claudiofantacci** [comment]
Assigned 🚀 
As I'm also working on `utils.h` and is now a template header-only utility file. As a consequence, please implement everything in the header and possibly/if needed as a template, otherwise let's talk f2f.

**Comment by claudiofantacci** [comment]
Closed by #60.
