### ISSUE TITLE
Uncoherent `skip`-related variable value in `*Prediction` classes

### ISSUE THREAD

**Issue by claudiofantacci** [robotology/bayes-filters-lib#63]
While refactoring here and there, I noticed that the `skip`-related variables in the `*Prediction` classes do not have coherent values when they are set in some specific ways. For example, in [`GaussianPrediction::skip`](https://github.com/robotology/bayes-filters-lib/blob/0241561a7ca133eaca5b7e62576770b3005696a3/src/BayesFilters/src/GaussianPrediction.cpp#L38-L50) if one set `skip_prediction_` the `skip_state_` and `skip_exogenous_` are not set as well with the same `status`. `skip_state_` and `skip_exogenous_` are meant to be used inside `predictionStep` and hence they could not be set as `skip_prediction_` works at a higher level, i.e. in the `prediction` method. However. I think this could lead to error if one first set `skip_state_`, then set and unset `skip_prediction_`. As an user, I would expect the prediction to be completely resumed while insted `skip_state_` would be still `true`. In the end, I propose to unify the behaviour to disambiguate the relationship between the variables as follow:
```cpp
    if (what_step == "prediction")
    {
        skip_prediction_ = status;

        skip_state_ = status;
        skip_exogenous_ = status;
    }
    else if (what_step == "state")
    {
        skip_state_ = status;

        skip_prediction_ = skip_state_ & skip_exogenous_;
    }
    else if (what_step == "exogenous")
    {
        skip_exogenous_ = status;

        skip_prediction_ = skip_state_ & skip_exogenous_;
    }
```

What do you think @xEnVrE?

**Comment by xEnVrE** [comment]
I agree with this :+1:
