### ISSUE TITLE
Switch from current CI system to GitHub actions

### ISSUE THREAD

**Issue by xEnVrE** [robotology/bayes-filters-lib#83]
Right now, the CI system is not working properly:

- `Codacy` is not enabled on the `devel` branch
- `Travis CI` is working  properly with `gcc C++ ` and `clang C++` compilers but is failing with `Xcode` (reported error is: `the command "which ccache" failed and exited with 1 during .`)

Although fixing these errors is doable, it is probably better to spend some time to move the CI system to GitHub actions.

**Comment by claudiofantacci** [comment]
Agreed :-) Thanks for reporting!

**Comment by xEnVrE** [comment]
Addressed in #87
