### ISSUE TITLE
About the const-ness of some methods of class MeasurementModel

### ISSUE THREAD

**Issue by xEnVrE** [robotology/bayes-filters-lib#84]
I am opening this issue to discuss about the const-ness of some methods belonging to the class `bfl::MeasurementModel`.

Usually, we require users to call
1. `MeasurementModel::freeze()` in order to store their measurements somewhere;
2. `MeasurementModel::measure() const` to get those measurements;
3. `MeasurementModel::predictedMeasure(current_state&) const` to predict measurements given the current state `current_state`.

As indicated, methods (2) and (3) are const.

Sometimes, when working with images, it may happen that the measurements **and/or the predicted measurements** are not available for all the pixels belonging to the image (or the part of the image we are interested in). In this situation, in order to use all the correction class that we already implemented in the library without modifications, we would like to
1. within `freeze`, discard the invalid measurements and store only the valid ones;
2. within `predictedMeasure` discard the invalid predicted measurements but also those for which we do not have a valid measurement. Finally we would also like to discard those measurements for which we do not have a valid prediction.

This way, we can obtain two entities, one measured and one predicted, that are one-to-one and can be used, e.g., to evaluate an innovation in any of the Kalman-based corrections.

Unfortunately, this configuration is not possible because `MeasurementModel::predictedMeasure()` is const. On the other hand, removing `const` does not seem to me the best solution. In fact, this way the user would be allowed to modify the measurements after the call to  `freeze()` and we should force users to call `measure()` only after `predictedMeasure()` to be sure that everything is consistent.

What do you think?

**Comment by claudiofantacci** [comment]
As a general note, I'm not sure this problem is correctly framed.
My feeling is that we are lacking a `preoprocess` function/hook somewhere to modify the data from `freeze` and `predictedMeasure`, but on the filter side, where a copy of the measurements is most likely to be present.

The problem is that the invalid measurements are a problem of the downstream task, not of the measurement process per se. Same goes for the predicted measurements.

> we should force users to call `measure()` only after `predictedMeasure()` to be sure that everything is consistent.

Not sure to have understood this sentence.

**Comment by xEnVrE** [comment]
> As a general note, I'm not sure this problem is correctly framed.
My feeling is that we are lacking a preoprocess function/hook somewhere to modify the data from freeze and predictedMeasure, but on the filter side, where a copy of the measurements is most likely to be present.

I agree with this solution. However, if the solution is on the filter side, it might be the case that the filter needs additional information (most likely stored within the measurement model) to decide how to invalidate measurements and/or prediction. Then we should decide how to transfer these additional information to the filter or how to standardize the procedure (if possible).

> > we should force users to call measure() only after predictedMeasure() to be sure that everything is consistent.
> Not sure to have understood this sentence.

I was trying to explain that allowing changes to the measurements inside `predictedMeasure()` is dangerous because if the final user calls `measure()` before `predictedMeasure()` then they will miss the change in the measurements. For this reason, my proposal to remove const-ness from `predictedMeasure()` is for sure not to be considered. Also, the name `predictedMeasure()` would be misleading because the user is not expecting that this method can change the measurements.

**Comment by claudiofantacci** [comment]
> I agree with this solution. However, if the solution is on the filter side, it might be the case that the filter needs additional information (most likely stored within the measurement model) to decide how to invalidate measurements and/or prediction. Then we should decide how to transfer these additional information to the filter or how to standardize the procedure (if possible).

Could be a hook or something implementable on the measurement process. A wrapper/decorator or by implementing a function that normally does nothing.

**Comment by xEnVrE** [comment]
If ok with you, I would close this issue and open a new one with a proper title so that we can track this missing feature.
